version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/data:/opt/keycloak/data/
    networks:
      - keycloak

  express:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - KEYCLOAK_CLIENT_SECRET=mysecret
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
    volumes:
      - ".:/app"
    networks:
      - keycloak

networks:
  keycloak:
